### ISSUE TITLE
bad handling of invalid/inaccessible namespaces

### ISSUE THREAD

**Issue by KlavsKlavsen** [gkarthiks/container-resource-exporter#5]
I Accidently gave it an ENV with invalid namespace names in it (using the mulitple namespaces support) - and it threw up:
```
time="2020-08-10T06:02:53Z" level=info msg="Scraping core and metrics api for metrics"
time="2020-08-10T06:02:53Z" level=info msg="Currently scrapping the $NS_GATEWAY_BANK namespace"
time="2020-08-10T06:02:53Z" level=info msg="Currently scrapping the $NS_GATEWAY_WEB namespace"
time="2020-08-10T06:02:53Z" level=info msg="Currently scrapping the $NS_MANAGER namespace"
time="2020-08-10T06:02:53Z" level=info msg="Currently scrapping the $NS_PORTAL namespace"
time="2020-08-10T06:02:53Z" level=info msg="Currently scrapping the $NS_ANALYTICS namespace"
time="2020-08-10T06:02:53Z" level=error msg="pods is forbidden: User \"system:serviceaccount:api-klavs2-manager-d1:api-prometheus-container-resource-exporter-klavs2\" cannot list pods in the namespace \"$NS_ANALYTICS\": no RBAC policy matched"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1212559]

goroutine 10 [running]:
k8s.io/metrics/pkg/client/clientset/versioned.(*Clientset).MetricsV1beta1(...)
        /go/pkg/mod/k8s.io/metrics@v0.18.2/pkg/client/clientset/versioned/clientset.go:52
main.(*Exporter).Collect(0xc000421000, 0xc0004a08a0)
        /go/src/github.com/gkarthiks/container-resource-exporter/container_resource_exporter.go:184 +0x569
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:444 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:455 +0x599
                                                                                                                                                                 
```

**Comment by KlavsKlavsen** [comment]
It also dies if I give it valid namespaces:
```
time="2020-08-10T06:27:57Z" level=info msg="Currently scrapping the api-klavs2-portal-d1 namespace"
time="2020-08-10T06:27:57Z" level=info msg="Currently scrapping the api-klavs2-analytics-d1 namespace"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1212559]

goroutine 42 [running]:
k8s.io/metrics/pkg/client/clientset/versioned.(*Clientset).MetricsV1beta1(...)
        /go/pkg/mod/k8s.io/metrics@v0.18.2/pkg/client/clientset/versioned/clientset.go:52
main.(*Exporter).Collect(0xc00041e280, 0xc0004a4120)
        /go/src/github.com/gkarthiks/container-resource-exporter/container_resource_exporter.go:184 +0x569
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:444 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:536 +0xe36
```

**Comment by KlavsKlavsen** [comment]
@gkarthiks I can see the cause.. it fails on analytics namespace - because result set is empty (there are no pods in that namespace in this test env).

**Comment by KlavsKlavsen** [comment]
It looks this would be the place it fails: https://github.com/gkarthiks/container-resource-exporter/blob/master/container_resource_exporter.go#L147 <- where you append pod.Items - but if there are no pods - thats going to be empty.. so you should probably just wrap it in a null check ?

**Comment by KlavsKlavsen** [comment]
Its actually this, which is fed a complete string of all domains (instead of just one namespace which is what its supposed to get):
https://github.com/gkarthiks/container-resource-exporter/blob/master/container_resource_exporter.go#L184 - in the multi-namespace situation.

**Comment by KlavsKlavsen** [comment]
I tried to make a loop like you do with Pods at #147 - but since I've never coded Go before - it has proven not easy to do :(
I figured I should put podMetrics inside a variable of type PodMetricsList - and the use that.. Haven't gotten it working though :(

**Comment by gkarthiks** [comment]
@KlavsKlavsen  both of them are valid observations. I will fix that this week end. Thank you for being kind and patient! :)

**Comment by WyriHaximus** [comment]
Not sure if this is caused by the same issue, but I'm getting the same error before mentioning of any specific namespaces:

```
│ time="2020-08-16T11:15:14Z" level=info msg="No watch namespace provided, defaulting to cluster level"                                                                                                   │
│ time="2020-08-16T11:15:14Z" level=info msg="Serving on port :9000"                                                                                                                                      │
│ time="2020-08-16T11:15:30Z" level=info msg="Running healthz check"                                                                                                                                      │
│ time="2020-08-16T11:15:31Z" level=info msg="Running healthz check"                                                                                                                                      │
│ time="2020-08-16T11:15:41Z" level=info msg="Scraping core and metrics api for metrics"                                                                                                                  │
│ panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                 │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1212559]                                                                                                                                │
│ goroutine 15 [running]:                                                                                                                                                                                 │
│ k8s.io/metrics/pkg/client/clientset/versioned.(*Clientset).MetricsV1beta1(...)                                                                                                                          │
│     /go/pkg/mod/k8s.io/metrics@v0.18.2/pkg/client/clientset/versioned/clientset.go:52                                                                                                                   │
│ main.(*Exporter).Collect(0xc0003ac040, 0xc00039ede0)                                                                                                                                                    │
│     /go/src/github.com/gkarthiks/container-resource-exporter/container_resource_exporter.go:184 +0x569                                                                                                  │
│ github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()                                                                                                                               │
│     /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:444 +0x19d                                                                                                            │
│ created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather                                                                                                                            │
│     /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:536 +0xe36                                                                                                            │
│ stream closed                                                                                                                                                                                           │
│                 
```

**Comment by gkarthiks** [comment]
@KlavsKlavsen @WyriHaximus have released the 0.2.1 version. That should fix these issues. Please try and let me know.

**Comment by WyriHaximus** [comment]
@gkarthiks Works for me now, thanks 👍

**Comment by KlavsKlavsen** [comment]
@gkarthiks I noticed that your latest tag and 0.2.1 is not the same digest (and docker also pulls a diff. layer when pulling latest - even though I just pulled 0.2.1).. ?

**Comment by gkarthiks** [comment]
@KlavsKlavsen that's weird, it should be the same. The `latest` is on master and my tag `0.2.1` is also cut from master. Theoretically both should be same with diff tags. But I am not sure hoe docker automated build works. FWIW, I can re-trigger the `latest` tag build if needed.
